name: Emulator

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  macos:
    runs-on: macos-26
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4
        with:
          install_args: python
      - name: Install build dependencies
        run: brew install glib pkgconf
      - name: Build
        run: mise run build
      - name: Test
        run: mise run test
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: fm1-emulator-macos-arm64
          path: .cache/fm1-emulator-macos-arm64.tar.gz
          if-no-files-found: error
